### ISSUE TITLE
Why multiply 2 on the partial value? 

### ISSUE THREAD

**Issue by twmht** [thughost2/Padam#1]
Hi,

thanks for this excellent work.

I have one question about the source code.

https://github.com/thughost2/Padam/blob/master/Padam.py#L86

Why did you multiply 2 on the partial value? You did not do that in the paper.

**Comment by jinghuichen** [comment]
Thank you for your interests in our work!

Note that the "denom" is already the square root of the second order momentum (see
https://github.com/thughost2/Padam/blob/master/Padam.py#L78).

Therefore the power of 2p gives you exactly what we described in the paper. We implement in this way simply want to follow the framework of the original amsgrad implementation in Pytorch and make minimum changes.

**Comment by twmht** [comment]
I may check the paper again.

thank you.
