### ISSUE TITLE
hyperparameter of SGDM for imagenet

### ISSUE THREAD

**Issue by AlanShao-zy** [thughost2/Padam#5]
Can you provide the hyperparameter weight_decay of SGDM for imagenet?
I find that with default value 1e-4, SGDM achieves a 69.758% accuracy with resnet18 (epoch is 90, LR schedule is at 30 60)
However, the accuracy reported in your paper is 70.23%.
Is it caused by the last 10 epochs or a different weight_decay hyperparameter?

**Comment by jinghuichen** [comment]
We use standard settings 1e-4 for Imagenet experiments. The gap is quite close so I guess it might just because of randomization issues. If you try another around, it may just get you 70%

**Comment by AlanShao-zy** [comment]
Thanks for reply
